get latest changelogs by providing latest version tag
standup-raven/what-the-changelog pull request #1
Opened 2019-06-27 05:04 UTC by jatinjtg

2019-06-28 09:54 UTC, ghost requested changes

2019-06-28 09:54 UTC, harshilsharma63 commented on src/run.ts
> +    if (!Config.currentTag || Config.currentTag === undefined) {
`!Config.currentTag` includes `Config.currentTag === undefined`. We can remove the later condition.

2019-06-28 09:54 UTC, harshilsharma63 commented on src/run.ts
> +        console.error('Invalid current tag');
How about `Current tag doesn't exist, tag: <tag>`? Invalid is not really the correct terminology here.

2019-06-28 09:54 UTC, harshilsharma63 commented on src/run.ts
> +    if (Config.previousTag) {
Add an empty line between two `if` blocks. Also, how about integrating a linter?

2019-06-28 09:54 UTC, harshilsharma63 commented on src/run.ts
> +    if(!Config.previousTag) {
I think we can simply use `else` here.

2019-06-28 09:54 UTC, harshilsharma63 commented on src/run.ts
> +    if (!Config.currentTag || Config.currentTag === undefined) {
Lets see if we can modularize this logic?

2019-06-28 12:53 UTC, jatinjtg commented on src/run.ts
> +    if (!Config.currentTag || Config.currentTag === undefined) {
Done

2019-06-28 12:53 UTC, jatinjtg commented on src/run.ts
> +        console.error('Invalid current tag');
Done

2019-06-28 12:53 UTC, jatinjtg commented on src/run.ts
> +    if(!Config.previousTag) {
Done

2019-06-28 12:53 UTC, jatinjtg commented on src/run.ts
> +    if (!Config.currentTag || Config.currentTag === undefined) {
Done

2019-06-28 12:54 UTC, jatinjtg commented on src/run.ts
> +    if (Config.previousTag) {
Done

2019-06-28 12:56 UTC, jatinjtg commented on src/run.ts
> +    if (Config.previousTag) {
I have integrated tslint .It dosen't allows whitespace

2019-07-01 07:22 UTC, harshilsharma63 commented on src/run.ts
> +    if (Config.previousTag) {
You must be having a space in that blank line. Maybe that's causing the error?

2019-07-01 07:23 UTC, ghost approved these changes

2019-07-01 07:26 UTC, jatinjtg commented on src/run.ts
> +    if (Config.previousTag) {
Okay.

2019-07-01 07:33 UTC, merged